
import Head from "next/head";
import { createMakeStyle } from "tss-react";
import { useTheme } from "../shared/theme";

const { TssProviderForSsr, makeStyles } = createMakeStyle({ useTheme });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TssProviderForSsr>
        <App />
      </TssProviderForSsr>
    </>
  )
}

const { useStyles } = makeStyles()(
  theme => ({
    "root": {
      "& > h1:nth-child(2)": {
        "color": theme.limeGreen
      }
    }
  })
);

function App() {

  const { classes } = useStyles();

  return (
    <div className={classes.root}>
      <h1>black</h1>
      <h1>Should be lime green</h1>
      <h1>black</h1>
    </div>
  );

}

/*
import Head from "next/head";
import {
  basicStyles,
  otherStyles,
  someMoreBasicStyles,
  someCssAsObject,
  combinedAsArray,
  cxExample,
  keyframesExample,
} from "../shared/styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Emotion Vanilla example</h1>
        <div className={basicStyles}>Basic styles using emotion</div>
        <div className={otherStyles}>Some more styles using emotion</div>
        <div className={someMoreBasicStyles}>Well why not here is some more</div>
        <div className={someCssAsObject}>Object styles using emotion css</div>
        <div className={combinedAsArray}>Array of styles using emotion css</div>
        <div className={cxExample}>cx example from emotion</div>
        <div className={keyframesExample} />
      </div>
    </>
  )
}
*/

/*
import Head from "next/head";
import { cache } from "../shared/cache";
import { CacheProvider } from "@emotion/react";
import { ClassNames } from "@emotion/react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CacheProvider value={cache}>
        <App />
      </CacheProvider>

    </>
  )
}

function App() {

  return (
    <ClassNames>
      {({ css }) =>
        <div className={css({ "& > h1:nth-child(2)": { "color": "green" } })}>
          <h1>foo</h1>
          <h1>bar</h1>
          <h1>baz</h1>
        </div>
      }
    </ClassNames>
  );

}
*/
